write_config:
  fields:
    device_id:
      required: true
      example: "b40f1f45d28b0891fe8d"
      selector:
        device:
          integration: "esphome"
    page_name:
      required: true
      example: "Main page"
      selector:
        text:
          type: text
    widget_1:
      required: false
      selector:
        entity:
          domain: "switch"
